site:
  name: PC Studios
  site: 'https://pcstudiosgames.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: PC Studios Games
    template: '%s â€” PC Studios'
  description: "Estudio independiente de desarrollo de videojuegos. Explora nuestros proyectos, noticias y diarios de desarrollo oficiales."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: PC Studios Games
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Cambiado para que el click funcione correctamente
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # o "G-XXXXXXXXXX"

ui:
  theme: 'dark' # Te lo he puesto en "dark" por defecto, que queda mejor para juegos
